name: project_2cp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dropdown_button2: ^2.3.9
  google_fonts: ^6.2.1
  get: ^4.6.6
  http: ^1.3.0
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  flutter_secure_storage: ^8.0.0 # <-- Updated here
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  riverpod_generator: ^2.6.5

flutter:
  uses-material-design: true

  assets:
    - assets/pizza.png
    - assets/client.png
    - assets/deliv.png
    - assets/resto.png
    - assets/congrats.png
    - assets/ch.jpg
    - assets/chef.jpg
    - assets/rich.jpg
    - assets/icon.png
    - assets/dorse.jpeg
    - assets/BBQ.jpg
    - assets/pasta_salad.jpg
    - assets/pizza2.jpg
    - assets/salamon.jpg
    - assets/salad.jpg
    - assets/restaurant.jpg
    - assets/person1.jpg
    - assets/person2.jpg
    - assets/person3.jpg
    - assets/person4.jpg
    - assets/person5.jpg
    - assets/person6.jpg
    - assets/cat.jpg
    - assets/res1.png
    - assets/res2.png
    - assets/res3.png
    - assets/res4.png
    - assets/background.avif