name: project_2cp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  get: ^4.6.6
  http: ^1.3.0
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  riverpod_generator: ^2.6.5

flutter:
  uses-material-design: true

  assets:
    - assets/pizza.png
    - assets/client.png
    - assets/deliv.png
    - assets/resto.png
    - assets/congrats.png
    - assets/ch.jpg
    - assets/chef.jpg
    - assets/rich.jpg
    - assets/icon.png
